Completed html-tables exercise.
Edward-J-Kim/rc0323-code-solutions pull request #18
Opened 2023-03-28 18:27 UTC by Edward-J-Kim

<img width="1218" alt="Screenshot 2023-03-28 at 11 21 03 AM" src="https://user-images.githubusercontent.com/126144853/228332597-b2d256a3-a2e4-45d7-909e-78e58406e5a4.png">

2023-03-28 18:33 UTC, robgmerrill requested changes
Close. For best practice you should include the `thead` and `tbody` elements.

2023-03-28 18:33 UTC, robgmerrill commented on html-tables/index.html
> +    <tr>
lines 12-16 should be wrapped in a `thead` element
```
<thead>
  <tr>
    <th>Student Name</th>
    <th>Course</th>
    <th>Grade</th></tr>
  </tr>
</thead>

2023-03-29 20:25 UTC, Edward-J-Kim commented on html-tables/index.html
> +    <tr>
Updated :)

2023-03-29 21:22 UTC, robgmerrill approved these changes
👍

2023-03-29 21:25 UTC, merged